package com.project.ui.Locators;

import org.openqa.selenium.By;

public class Page_Locators {

    public static final By VerifyHomePage = By.xpath("//section[@id='slider']");
    public static final By ClickOnSignupLogin = By.xpath("//a[normalize-space()='Signup / Login']");
    public static final By VerifyNewUserSignup = By.xpath("//h2[normalize-space()='New User Signup!']");
    public static final By VerifyEnterAccountInformation = By.xpath("//b[normalize-space()='Enter Account Information']");
    public static final By EnterName = By.xpath("//input[@placeholder='Name']");
    public static final By EnterEmail = By.xpath("//input[@data-qa='signup-email']");
    public static final By ClickOnSignupButton = By.xpath("//button[normalize-space()='Signup']");
    public static final By SelectTitleMr = By.id("id_gender1");
    public static final By SelectTitleMrs = By.id("id_gender2");
    public static final By SetPassword = By.id("password");
    public static final By SelectDay = By.id("days");
    public static final By SelectMonth = By.id("months");
    public static final By SelectYear = By.id("years");
    public static final By SignupNewsletter = By.id("newsletter");
    public static final By SignupSpecialOffers = By.id("optin");
    public static final By EnterFirstName = By.id("first_name");
    public static final By EnterLastName = By.id("last_name");
    public static final By EnterCompanyName = By.id("company");
    public static final By EnterAddress1 = By.id("address1");
    public static final By EnterAddress2 = By.id("address2");
    public static final By SelectCountry = By.id("country");
    public static final By EnterState = By.id("state");
    public static final By EnterCity = By.id("city");
    public static final By EnterZipcode = By.id("zipcode");
    public static final By EnterMobileNumber = By.id("mobile_number");
    public static final By ClickOnCreateAccountButton = By.xpath("//button[normalize-space()='Create Account']");
    public static final By DeleteAccount = By.xpath("//a[normalize-space()='Delete Account']");
    public static final By VerifyAccountCreated=By.xpath("//b[normalize-space()='Account Created!']");
    public static final By EnterLoginEmail = By.xpath("//input[@data-qa='login-email']");
    public static final By EnterLoginPassword = By.xpath("//input[@placeholder='Password']");
    public static final By ClickOnLogin = By.xpath("//button[normalize-space()='Login']");
    public static final By VerifyLoggedInAsUsername = By.xpath("//i[@class='fa fa-user']");
    public static final By ClickOnLogout = By.xpath("//a[normalize-space()='Logout']");
    public static final By VerifyAccountDeleted=By.xpath("//b[normalize-space()='Account Deleted!']");
    public static final By ClickOnContactUs = By.xpath("//a[normalize-space()='Contact us']");
    public static final By EnterContactEmail = By.xpath("//input[@placeholder='Email']");
    public static final By EnterSubject = By.xpath("//input[@placeholder='Subject']");
    public static final By EnterMessage = By.id("message");
    public static final By Uploadfile = By.xpath("//input[@name='upload_file']");
    public static final By ClickOnSubmit = By.xpath("//input[@name='submit']");
    public static final By ClickOnHome = By.xpath("//a[normalize-space()='Home']");
    public static final By ClickOnTestCase = By.xpath("//a[contains(text(),'Test Cases')]");
    public static final By VerifyLoginToYourAccount=By.xpath("//h2[normalize-space()='Login to your account']");
    public static final By VerifyWrongCredentials=By.xpath("//p[normalize-space()='Your email or password is incorrect!']");
    public static final By VerifyExistingUserSignup=By.xpath("//p[normalize-space()='Email Address already exist!']");
    public static final By VerifyGetInTouch=By.xpath("//h2[normalize-space()='Get In Touch']");
    public static final By VerifySuccessMessage=By.xpath("//div[contains(@class, 'alert-success') or contains(@class, 'status alert')]//span | //div[contains(@class, 'alert-success') or contains(@class, 'status alert')]");
    public static final By ClickOnProductPage=By.cssSelector("a[href='/products']");
    public static final By VerifyAllProductVisible=By.xpath("//h2[normalize-space()='All Products']");
    public static final By VerifyProductListIsVisible=By.xpath("//div[@class='features_items']");
    public static final By ClickOnViewProduct=By.xpath("(//a[normalize-space()='View Product' and contains(@href,'/product_details/1')])[1]");
    public static final By VerifyProductInfo=By.xpath("//div[@class='product-information']");
    public static final By SearchProduct=By.id("search_product");
    public static final By ClickOnContinue=By.xpath("//a[normalize-space()='Continue']");
    public static final By ClickOnSearchButton=By.id("submit_search");
    public static final By VerifySearchedProductIsVisible=By.xpath("//h2[normalize-space()='Searched Products']");
    public static final By VerifySubscription=By.xpath("//h2[normalize-space()='Subscription']");
    public static final By EnterSubscribeEmail=By.id("susbscribe_email");
    public static final By ClickOnArrowButton=By.xpath("//i[@class='fa fa-arrow-circle-o-right']");
    public static final By VerifySuccessfullSubscription=By.xpath("//div[contains(@class, 'alert-success')] | //span[contains(text(), 'successfully subscribed')]//ancestor::div[contains(@class, 'alert')]");
    public static final By ClickOnCart=By.xpath("//a[normalize-space()='Cart']//i[@class='fa fa-shopping-cart']");
    public static final By AddFirstProductToCart=By.xpath("(//a[contains(@class,'add-to-cart') and normalize-space()='Add to cart'])[1]");
    public static final By ClickOnContinueShopping=By.xpath("//button[normalize-space()='Continue Shopping']");
    public static final By AddSecondProductToCart=By.xpath("(//a[contains(@class,'add-to-cart') and normalize-space()='Add to cart'])[3]");
    public static final By ClickOnViewCart=By.xpath("//u[normalize-space()='View Cart']");
    public static final By EnterQuantity=By.xpath("//input[@id='quantity']");
    public static final By ClickOnAddToCart=By.xpath("//button[normalize-space()='Add to cart']");
    public static final By VerifyQuantity=By.xpath("//button[normalize-space()='5']");
    public static final By ClickOnProceedToCheckout=By.xpath("//a[normalize-space()='Proceed To Checkout']");
    public static final By ClickOnRegisterLogin=By.xpath("//u[normalize-space()='Register / Login']");
    public static final By ClickOnPlaceOrder=By.xpath("//a[normalize-space()='Place Order']");
    public static final By EnterNameOnCard=By.xpath("//input[@name='name_on_card']");
    public static final By EnterCardNumber=By.xpath("//input[@name='card_number']");
    public static final By EnterCVC=By.xpath("//input[@name='cvc']");
    public static final By EnterExpirationMonth=By.xpath("//input[@name='expiry_month']");
    public static final By EnterExpirationYear=By.xpath("//input[@name='expiry_year']");
    public static final By ClickOnPay=By.id("submit");
    public static final By VerifyOrderPlaced=By.xpath("//h2[normalize-space()='Order Placed!']");           
    public static final By VerifyCartPage=By.id("cart_items");
    public static final By RemoveProduct=By.xpath("(//a[@class='cart_quantity_delete'])[1]");
    public static final By ClickOnWomen=By.xpath("//a[normalize-space()='Women']");
    public static final By ClickOnDress=By.xpath("//a[normalize-space()='Dress']");
    public static final By VerifyWomenTopProducts=By.xpath("//h2[normalize-space()='Women - Dress Products']");
    public static final By ClickOnMen=By.xpath("//a[normalize-space()='Men']");
    public static final By ClickOnTshirts=By.xpath("//a[normalize-space()='Tshirts']");
    public static final By VerifyMenTopProducts=By.xpath("//h2[normalize-space()='Men - Tshirts Products']");
    public static final By VerifyBrands=By.xpath("//h2[normalize-space()='Brands']");
    public static final By ClickOnHM=By.xpath("//a[@href='/brand_products/H&M']");
    public static final By VerifyBrandNameHM=By.xpath("//h2[normalize-space()='Brand - H&M Products']");
    public static final By ClickOnPolo=By.xpath("//a[@href='/brand_products/Polo']");
    public static final By VerifyBrandNamePolo=By.xpath("//h2[normalize-space()='Brand - Polo Products']");
    public static final By VerifyWriteYourReviewVisible=By.xpath("//a[normalize-space()='Write Your Review']");
    public static final By EnterReviewName=By.id("name");
    public static final By EnterReviewEmail=By.id("email");
    public static final By EnterReviewText=By.id("review");
    public static final By SubmitReview=By.id("button-review");
    public static final By VerifyThankYouForYourReview=By.xpath("//span[contains(text(), 'Thank you')] | //div[contains(text(), 'Thank you')] | //p[contains(text(), 'Thank you')]//span");  
    public static final By DownloadInvoice=By.xpath("//a[normalize-space()='Download Invoice']"); 
}
